### ISSUE TITLE
Data Market V2 Port - Use Cases

### ISSUE THREAD

**Issue by Seth-Schmidt** [PowerLoom/snapshotter-core#15]
This is a master issue for tracking the porting of specific use cases to the V2 snapshotter architecture. 

- [x] ETH UniswapV2

- [x] ETH UniswapV3

- [x] Base UniswapV2

- [x] Base UniswapV3

- [x] ETH AaveV3

- [x] Base AaveV3

**Comment by xadahiya** [comment]
Initial implementation is done as shared in https://powerloomhq.slack.com/archives/C06RRBMA3F1/p1729046849889699, moving to testing and review phase.

**Comment by xadahiya** [comment]
Moving to the current iteration for review.
